# Generated by Django 4.1.2 on 2022-10-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_words", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="word",
            name="unique_word_per_room",
        ),
        migrations.AddConstraint(
            model_name="word",
            constraint=models.UniqueConstraint(fields=("room", "word"), name="unique_word_per_room"),
        ),
    ]
