# Generated by Django 4.1.2 on 2022-10-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_words", "0002_remove_word_unique_word_per_room_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="word",
            name="unique_word_per_room",
        ),
        migrations.AddConstraint(
            model_name="word",
            constraint=models.UniqueConstraint(
                fields=("room", "word"),
                name="unique_word_per_room",
                violation_error_message="Unique word must be provided",
            ),
        ),
    ]
